# Real projects discovered on this server — curated for the portfolio.

PORTFOLIO = [
    {
        "id": "lillymerg",
        "name": "LillyOS — War Room",
        "description": "Multi-department corporate AI platform with 8 departments, AI agents, sprint management, Kanban ticketing, drag-drop theme editor, Synapse intelligence mapper, and Lilly — an intelligent conversational Chief of Staff with web search, delegation, TTS voice, and autonomous tasklet workers.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["Python", "FastAPI", "React", "Vite", "Ollama", "Redis", "Edge TTS", "Docker", "Nginx", "faster-whisper"],
        "features": ["8 departments with AI agents", "Lilly Chat with TTS voice", "Autonomous tasklet workers", "Synapse intelligence mapper", "Sprint/ticket management", "Design system editor", "Self-healing system", "SSE real-time events"],
        "screenshot": "/screenshots/lillymerg.png",
        "live_url": "http://100.93.131.114:3006",
        "source_path": "/home/labhrasd/LillyMerg",
        "achievements": ["36 AI agents across 8 departments", "Auto-creates sprints and progresses tickets", "LLM-powered chat with web search and delegation", "Real-time event streaming to browser notifications"],
        "created": "2026-Q1",
    },
    {
        "id": "lillyos",
        "name": "LillyOS AI Assistant",
        "description": "Full-stack AI chatbot with real-time Three.js shader visualization. Features a neural ring shader that reacts to conversation emotion vectors, voice wake-word detection ('Hey Lilly'), Piper TTS voice synthesis, and an Ollama LLM backend. The UI renders a GLSL shader that pulses and shifts color based on sentiment analysis of the conversation.",
        "type": "web_app",
        "status": "archived",
        "tech_stack": ["Python", "FastAPI", "React", "Three.js", "GLSL", "Ollama", "Piper TTS", "Docker"],
        "features": ["Real-time emotion-reactive shader", "Voice wake-word detection", "Piper TTS voice output", "LLM conversation memory", "Custom model fine-tune file"],
        "screenshot": "/screenshots/lillyos.png",
        "source_path": "/home/labhrasd/lillyos",
        "achievements": ["Real-time GLSL shader animated by conversation sentiment", "Custom Ollama modelfile for tailored personality"],
        "created": "2025-Q4",
    },
    {
        "id": "lillyshader",
        "name": "Lilly-Shader",
        "description": "An AI-controlled real-time shader visualization web app. Users chat with an Ollama LLM which dynamically generates shader parameters — wave speed, noise amplitude, glow intensity, and color palette — streamed via WebSocket to a Vite+React frontend with a fullscreen GLSL canvas.",
        "type": "shader",
        "status": "archived",
        "tech_stack": ["Python", "FastAPI", "React", "Vite", "WebSocket", "GLSL", "Ollama", "Docker"],
        "features": ["AI-generated shader parameters", "Real-time WebSocket updates", "Fullscreen GLSL canvas", "Chat-controlled visuals"],
        "screenshot": "/screenshots/lillyshader.png",
        "source_path": "/home/labhrasd/Lilly-Shader",
        "achievements": ["LLM dynamically controls GPU shader parameters in real-time"],
        "created": "2025-Q4",
    },
    {
        "id": "spawn",
        "name": "SPAWN / LAR — Ferrofluid AI",
        "description": "An advanced AI voice assistant platform with a real-time ferrofluid simulation frontend. Features GPU particle simulation (SPH fluid dynamics, Voronoi height maps), audio-reactive visuals, webcam integration with TensorFlow.js and MediaPipe, and a full Piper TTS backend. The ferrofluid sim visually responds to AI speech like a liquid metal organism.",
        "type": "web_app",
        "status": "archived",
        "tech_stack": ["Python", "FastAPI", "React", "Three.js", "p5.js", "TensorFlow.js", "MediaPipe", "GLSL", "Piper TTS", "Ollama", "Docker"],
        "features": ["GPU ferrofluid simulation", "Audio-reactive particle system", "Webcam + vision integration", "Piper TTS voice", "Custom LLM persona"],
        "screenshot": "/screenshots/spawn.png",
        "source_path": "/home/labhrasd/SPAWN",
        "achievements": ["Real-time SPH fluid simulation driven by AI voice input", "Multi-modal: vision, audio, text, and simulation"],
        "created": "2025-Q4",
    },
    {
        "id": "keke-fileshare",
        "name": "Keke FileShare",
        "description": "A lightweight file sharing and hosting web application running on Nginx. Provides simple file upload and sharing capabilities for the local network.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["Nginx", "Docker"],
        "features": ["File upload", "Direct download links", "Simple web UI"],
        "screenshot": "/screenshots/keke_fileshare.png",
        "live_url": "http://100.93.131.114:8095",
        "source_path": "/home/labhrasd",
        "container_name": "keke_fileshare",
        "achievements": ["Lightweight file sharing running on local infrastructure"],
        "created": "2026-Q1",
    },
    {
        "id": "qwen-translate",
        "name": "Qwen Live Translate",
        "description": "Real-time language translation service powered by the Qwen LLM. Translates text between multiple languages with low latency, designed for live conversation scenarios.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["Python", "Qwen LLM", "Docker", "FastAPI"],
        "features": ["Real-time translation", "Multi-language support", "LLM-powered accuracy"],
        "screenshot": "/screenshots/qwen_translate.png",
        "live_url": "http://100.93.131.114:8091",
        "container_name": "qwen-live-translate",
        "achievements": ["Local LLM translation without external API dependencies"],
        "created": "2026-Q1",
    },
    {
        "id": "familywall",
        "name": "FamilyWall",
        "description": "A private family social network application for sharing updates, photos, and events within a closed family group. Self-hosted with persistent data storage.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["Node.js", "React", "Docker", "MongoDB"],
        "features": ["Family feed", "Photo sharing", "Event coordination", "Private access"],
        "screenshot": "/screenshots/familywall.png",
        "live_url": "http://100.93.131.114:8100",
        "container_name": "familywall-app",
        "achievements": ["Full-stack family social network running on private infrastructure"],
        "created": "2026-Q1",
    },
    {
        "id": "project-kiki",
        "name": "Project Kiki",
        "description": "A web application project deployed with Nginx, serving a custom-built interface. Part of the project-hosting ecosystem running on this server.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["HTML", "CSS", "JavaScript", "Nginx", "Docker"],
        "features": ["Custom web UI", "Nginx-hosted static content"],
        "screenshot": "/screenshots/project_kiki.png",
        "live_url": "http://100.93.131.114:8086",
        "container_name": "project-kiki",
        "achievements": ["Deployed as part of multi-project Docker ecosystem"],
        "created": "2026-Q1",
    },
    {
        "id": "media-gallery",
        "name": "Media Gallery",
        "description": "A self-hosted media gallery application for browsing and organizing images and videos. Provides a clean, responsive interface for personal media collections.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["Node.js", "React", "Docker"],
        "features": ["Image browsing", "Video playback", "Responsive gallery layout"],
        "screenshot": "/screenshots/media_gallery.png",
        "live_url": "http://100.93.131.114:8092",
        "container_name": "project-media-gallery",
        "achievements": ["Full media server with responsive UI running locally"],
        "created": "2026-Q1",
    },
    {
        "id": "ecommerce-store",
        "name": "E-Commerce Store Demo",
        "description": "A full e-commerce storefront demo application with product listings, cart functionality, and checkout flow. Demonstrates modern web commerce capabilities running on local infrastructure.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["Node.js", "React", "Docker"],
        "features": ["Product catalog", "Shopping cart", "Checkout flow"],
        "screenshot": "/screenshots/ecommerce_store.png",
        "live_url": "http://100.93.131.114:8085",
        "container_name": "project-ecommerce-store",
        "achievements": ["Full e-commerce stack running on private server"],
        "created": "2026-Q1",
    },
    {
        "id": "trading-bot-ui",
        "name": "Trading Bot Dashboard",
        "description": "A trading bot monitoring dashboard with real-time portfolio tracking, trade history, and performance analytics. Provides visual insights into automated trading strategies.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["Node.js", "React", "Docker"],
        "features": ["Portfolio tracking", "Trade history", "Performance metrics"],
        "screenshot": "/screenshots/trading_bot.png",
        "live_url": "http://100.93.131.114:8089",
        "container_name": "project-trading-bot-ui",
        "achievements": ["Real-time trading dashboard with portfolio analytics"],
        "created": "2026-Q1",
    },
    {
        "id": "file-manager",
        "name": "File Manager",
        "description": "A web-based file management application for browsing, uploading, and organizing files on the server through a clean browser interface.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["Python", "Flask", "Docker"],
        "features": ["File browse", "Upload/download", "Directory management"],
        "screenshot": "/screenshots/file_manager.png",
        "live_url": "http://100.93.131.114:8084",
        "container_name": "project-file-manager",
        "achievements": ["Full file management UI for server filesystem"],
        "created": "2026-Q1",
    },
    {
        "id": "taxhacker",
        "name": "TaxHacker",
        "description": "A tax preparation and optimization web application with PostgreSQL backend. Helps users organize and optimize their tax situation with guided workflows.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["Python", "FastAPI", "PostgreSQL", "Docker"],
        "features": ["Tax calculation", "Deduction optimization", "Guided workflow"],
        "screenshot": "/screenshots/taxhacker.png",
        "live_url": "http://100.93.131.114:7331",
        "container_name": "taxhacker",
        "achievements": ["Full-stack tax application with PostgreSQL persistence"],
        "created": "2026-Q1",
    },
    {
        "id": "wordpress-store",
        "name": "WordPress Store",
        "description": "A Bitnami WordPress deployment running an e-commerce or content site. Deployed with MariaDB database backend as part of the project ecosystem.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["WordPress", "PHP", "MariaDB", "Docker", "Bitnami"],
        "features": ["Content management", "Theme system", "Plugin support"],
        "screenshot": "/screenshots/wordpress_store.png",
        "live_url": "http://100.93.131.114:8090",
        "container_name": "lilly_store",
        "achievements": ["Production WordPress deployment with database backend"],
        "created": "2026-Q1",
    },
    {
        "id": "gitea",
        "name": "Gitea Git Hosting",
        "description": "Self-hosted Git repository hosting service powered by Gitea. Provides version control, issue tracking, and code review for all projects on the server — including all the source code for every portfolio project listed here.",
        "type": "infra",
        "status": "live",
        "tech_stack": ["Go", "Gitea", "Docker", "PostgreSQL"],
        "features": ["Git repository hosting", "Issue tracking", "Code review", "CI/CD integration"],
        "screenshot": "/screenshots/gitea.png",
        "live_url": "http://100.93.131.114:3000",
        "container_name": "gallery-gitea-gitea",
        "achievements": ["Self-hosted GitHub alternative powering the entire development ecosystem"],
        "created": "2026-Q1",
    },
    {
        "id": "jellyfin",
        "name": "Jellyfin Media Server",
        "description": "A self-hosted media streaming server running Jellyfin. Provides streaming of movies, TV shows, music, and photos to any device on the network with a rich web interface.",
        "type": "infra",
        "status": "live",
        "tech_stack": ["C#", "Jellyfin", "Docker"],
        "features": ["Media streaming", "Multi-device support", "User management", "Metadata lookup"],
        "screenshot": "/screenshots/jellyfin.png",
        "live_url": "http://100.93.131.114:8096",
        "container_name": "gallery-jellyfin-jellyfin",
        "achievements": ["Full media server with streaming to any device on the network"],
        "created": "2026-Q1",
    },
    {
        "id": "dify-platform",
        "name": "Dify AI Platform",
        "description": "An open-source LLM application development platform running Dify v1.14.2. Provides a visual workflow builder for creating AI applications with RAG, agent capabilities, and model management — all powered by the local Ollama instance.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["Python", "TypeScript", "React", "Dify", "PostgreSQL", "Redis", "Weaviate", "Docker"],
        "features": ["Visual AI workflow builder", "RAG pipeline", "Agent management", "Multi-model support"],
        "screenshot": "/screenshots/dify.png",
        "live_url": "http://100.93.131.114:9061",
        "container_name": "buildy-dify-nginx",
        "achievements": ["Full Dify AI platform deployment with local Ollama integration"],
        "created": "2026-Q2",
    },
    {
        "id": "buildy-seo",
        "name": "Buildy SEO Tool",
        "description": "An SEO analysis and optimization tool that helps audit website performance, meta tags, and search engine ranking factors. Part of the Buildy suite of development tools.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["Node.js", "React", "Docker"],
        "features": ["SEO audit", "Meta tag analysis", "Performance scoring"],
        "screenshot": "/screenshots/buildy_seo.png",
        "live_url": "http://100.93.131.114:9062",
        "container_name": "buildy-seo-tool",
        "achievements": ["Comprehensive SEO analysis tool as a local web service"],
        "created": "2026-Q2",
    },
    {
        "id": "dws-mern",
        "name": "DWS MERN App",
        "description": "A full-stack MERN (MongoDB, Express, React, Node.js) application deployed with Docker. Demonstrates the complete MERN stack with a RESTful API backend and React frontend, orchestrated with Docker Compose services.",
        "type": "web_app",
        "status": "live",
        "tech_stack": ["MongoDB", "Express", "React", "Node.js", "Docker"],
        "features": ["RESTful API", "React frontend", "MongoDB persistence", "Docker orchestration"],
        "screenshot": "/screenshots/dws_mern.png",
        "live_url": "http://100.93.131.114:5000",
        "container_name": "dws-server",
        "achievements": ["Full MERN stack deployed with Docker Compose multi-service architecture"],
        "created": "2026-Q2",
    },
    {
        "id": "local-llm-gui",
        "name": "Local LLM Chat GUI",
        "description": "A desktop GUI application built with Python CustomTkinter for chatting with local LLMs via Ollama. Features a synthwave/neon UI theme, session management, streaming responses, markdown rendering with code blocks, LangGraph conversation state management, model switching, and chat export.",
        "type": "desktop",
        "status": "archived",
        "tech_stack": ["Python", "CustomTkinter", "LangChain", "LangGraph", "Ollama"],
        "features": ["Synthwave neon UI", "Streaming responses", "Session management", "Markdown + code rendering", "Model switching", "Chat export"],
        "screenshot": "/screenshots/local_llm_gui.png",
        "source_path": "/home/labhrasd/Local-LLM-Chatbot-GUI-Ollama",
        "achievements": ["Full desktop LLM client with LangGraph state management"],
        "created": "2025-Q3",
    },
    {
        "id": "genesis",
        "name": "GENESIS Deployer",
        "description": "A Python deployment automation script that rebuilds and deploys the entire LillyOS project from scratch — cleaning Docker containers, building directory structures, generating backend/frontend source code, creating Dockerfiles, and orchestrating Docker Compose. Includes a system health diagnostic checker.",
        "type": "script",
        "status": "archived",
        "tech_stack": ["Python", "Docker", "subprocess"],
        "features": ["Zero-to-deployed automation", "System health diagnostics", "Source code generation"],
        "screenshot": "/screenshots/genesis.png",
        "source_path": "/home/labhrasd/GENESIS",
        "achievements": ["One-script deployment of complete full-stack AI platform"],
        "created": "2025-Q4",
    },
    {
        "id": "ader-quantizer",
        "name": "A-Der TurboQuant",
        "description": "An AI model quantization research project using the TurboQuant library. Experiments with polar quantization, QJL (quantized Johnson-Lindenstrauss), KV cache optimization, codebook techniques, rotation-based compression, outlier handling, and hardware replay analysis for efficient LLM inference.",
        "type": "library",
        "status": "archived",
        "tech_stack": ["Python", "TurboQuant", "NumPy", "SciPy"],
        "features": ["Polar quantization", "KV cache optimization", "Codebook compression", "Outlier handling"],
        "screenshot": "/screenshots/ader.png",
        "source_path": "/home/labhrasd/A-Der",
        "achievements": ["Advanced quantization research for efficient local LLM deployment"],
        "created": "2025-Q3",
    },
]
